.TH "httplib::detail::case_ignore::hash" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httplib::detail::case_ignore::hash
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBoperator()\fP (const std::string &key) const"
.br
.ti -1c
.RI "size_t \fBhash_core\fP (const char *s, size_t l, size_t h) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
