.TH "httplib::TaskQueue" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httplib::TaskQueue
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhttplib::ThreadPool\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBenqueue\fP (std::function< void()> fn)=0"
.br
.ti -1c
.RI "virtual void \fBshutdown\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBon_idle\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
