.TH "httplib::Client" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httplib::Client
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClient\fP (const std::string &scheme_host_port)"
.br
.ti -1c
.RI "\fBClient\fP (const std::string &scheme_host_port, const std::string &client_cert_path, const std::string &client_key_path)"
.br
.ti -1c
.RI "\fBClient\fP (const std::string &host, int port)"
.br
.ti -1c
.RI "\fBClient\fP (const std::string &host, int port, const std::string &client_cert_path, const std::string &client_key_path)"
.br
.ti -1c
.RI "\fBClient\fP (\fBClient\fP &&)=default"
.br
.ti -1c
.RI "\fBClient\fP & \fBoperator=\fP (\fBClient\fP &&)=default"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.ti -1c
.RI "\fBResult\fP \fBGet\fP (const std::string &path, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBGet\fP (const std::string &path, ContentReceiver content_receiver, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBGet\fP (const std::string &path, ResponseHandler response_handler, ContentReceiver content_receiver, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBGet\fP (const std::string &path, const Headers &headers, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBGet\fP (const std::string &path, const Headers &headers, ContentReceiver content_receiver, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBGet\fP (const std::string &path, const Headers &headers, ResponseHandler response_handler, ContentReceiver content_receiver, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBGet\fP (const std::string &path, const Params &params, const Headers &headers, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBGet\fP (const std::string &path, const Params &params, const Headers &headers, ContentReceiver content_receiver, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBGet\fP (const std::string &path, const Params &params, const Headers &headers, ResponseHandler response_handler, ContentReceiver content_receiver, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBHead\fP (const std::string &path)"
.br
.ti -1c
.RI "\fBResult\fP \fBHead\fP (const std::string &path, const Headers &headers)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const char *body, size_t content_length, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const std::string &body, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, size_t content_length, ContentProvider content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, ContentProviderWithoutLength content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const Params &params)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const UploadFormDataItems &items, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const Headers &headers)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const Headers &headers, const char *body, size_t content_length, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const Headers &headers, const std::string &body, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const Headers &headers, size_t content_length, ContentProvider content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const Headers &headers, ContentProviderWithoutLength content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const Headers &headers, const Params &params)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const Headers &headers, const UploadFormDataItems &items, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const Headers &headers, const UploadFormDataItems &items, const std::string &boundary, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const Headers &headers, const UploadFormDataItems &items, const FormDataProviderItems &provider_items, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPost\fP (const std::string &path, const Headers &headers, const std::string &body, const std::string &content_type, ContentReceiver content_receiver, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const char *body, size_t content_length, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const std::string &body, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, size_t content_length, ContentProvider content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, ContentProviderWithoutLength content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const Params &params)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const UploadFormDataItems &items, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const Headers &headers)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const Headers &headers, const char *body, size_t content_length, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const Headers &headers, const std::string &body, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const Headers &headers, size_t content_length, ContentProvider content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const Headers &headers, ContentProviderWithoutLength content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const Headers &headers, const Params &params)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const Headers &headers, const UploadFormDataItems &items, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const Headers &headers, const UploadFormDataItems &items, const std::string &boundary, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const Headers &headers, const UploadFormDataItems &items, const FormDataProviderItems &provider_items, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPut\fP (const std::string &path, const Headers &headers, const std::string &body, const std::string &content_type, ContentReceiver content_receiver, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const char *body, size_t content_length, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const std::string &body, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, size_t content_length, ContentProvider content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, ContentProviderWithoutLength content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const Params &params)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const UploadFormDataItems &items, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const Headers &headers)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const Headers &headers, const char *body, size_t content_length, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const Headers &headers, const std::string &body, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const Headers &headers, size_t content_length, ContentProvider content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const Headers &headers, ContentProviderWithoutLength content_provider, const std::string &content_type, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const Headers &headers, const Params &params)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const Headers &headers, const UploadFormDataItems &items, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const Headers &headers, const UploadFormDataItems &items, const std::string &boundary, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const Headers &headers, const UploadFormDataItems &items, const FormDataProviderItems &provider_items, UploadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBPatch\fP (const std::string &path, const Headers &headers, const std::string &body, const std::string &content_type, ContentReceiver content_receiver, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBDelete\fP (const std::string &path, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBDelete\fP (const std::string &path, const char *body, size_t content_length, const std::string &content_type, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBDelete\fP (const std::string &path, const std::string &body, const std::string &content_type, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBDelete\fP (const std::string &path, const Params &params, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBDelete\fP (const std::string &path, const Headers &headers, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBDelete\fP (const std::string &path, const Headers &headers, const char *body, size_t content_length, const std::string &content_type, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBDelete\fP (const std::string &path, const Headers &headers, const std::string &body, const std::string &content_type, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBDelete\fP (const std::string &path, const Headers &headers, const Params &params, DownloadProgress progress=nullptr)"
.br
.ti -1c
.RI "\fBResult\fP \fBOptions\fP (const std::string &path)"
.br
.ti -1c
.RI "\fBResult\fP \fBOptions\fP (const std::string &path, const Headers &headers)"
.br
.ti -1c
.RI "bool \fBsend\fP (\fBRequest\fP &req, \fBResponse\fP &res, Error &error)"
.br
.ti -1c
.RI "\fBResult\fP \fBsend\fP (const \fBRequest\fP &req)"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "std::string \fBhost\fP () const"
.br
.ti -1c
.RI "int \fBport\fP () const"
.br
.ti -1c
.RI "size_t \fBis_socket_open\fP () const"
.br
.ti -1c
.RI "socket_t \fBsocket\fP () const"
.br
.ti -1c
.RI "void \fBset_hostname_addr_map\fP (std::map< std::string, std::string > addr_map)"
.br
.ti -1c
.RI "void \fBset_default_headers\fP (Headers headers)"
.br
.ti -1c
.RI "void \fBset_header_writer\fP (std::function< ssize_t(\fBStream\fP &, Headers &)> const &writer)"
.br
.ti -1c
.RI "void \fBset_address_family\fP (int family)"
.br
.ti -1c
.RI "void \fBset_tcp_nodelay\fP (bool on)"
.br
.ti -1c
.RI "void \fBset_socket_options\fP (SocketOptions socket_options)"
.br
.ti -1c
.RI "void \fBset_connection_timeout\fP (time_t sec, time_t usec=0)"
.br
.ti -1c
.RI "template<class Rep , class Period > void \fBset_connection_timeout\fP (const std::chrono::duration< Rep, Period > &duration)"
.br
.ti -1c
.RI "void \fBset_read_timeout\fP (time_t sec, time_t usec=0)"
.br
.ti -1c
.RI "template<class Rep , class Period > void \fBset_read_timeout\fP (const std::chrono::duration< Rep, Period > &duration)"
.br
.ti -1c
.RI "void \fBset_write_timeout\fP (time_t sec, time_t usec=0)"
.br
.ti -1c
.RI "template<class Rep , class Period > void \fBset_write_timeout\fP (const std::chrono::duration< Rep, Period > &duration)"
.br
.ti -1c
.RI "void \fBset_max_timeout\fP (time_t msec)"
.br
.ti -1c
.RI "template<class Rep , class Period > void \fBset_max_timeout\fP (const std::chrono::duration< Rep, Period > &duration)"
.br
.ti -1c
.RI "void \fBset_basic_auth\fP (const std::string &username, const std::string &password)"
.br
.ti -1c
.RI "void \fBset_bearer_token_auth\fP (const std::string &token)"
.br
.ti -1c
.RI "void \fBset_keep_alive\fP (bool on)"
.br
.ti -1c
.RI "void \fBset_follow_location\fP (bool on)"
.br
.ti -1c
.RI "void \fBset_path_encode\fP (bool on)"
.br
.ti -1c
.RI "void \fBset_url_encode\fP (bool on)"
.br
.ti -1c
.RI "void \fBset_compress\fP (bool on)"
.br
.ti -1c
.RI "void \fBset_decompress\fP (bool on)"
.br
.ti -1c
.RI "void \fBset_interface\fP (const std::string &intf)"
.br
.ti -1c
.RI "void \fBset_proxy\fP (const std::string &host, int port)"
.br
.ti -1c
.RI "void \fBset_proxy_basic_auth\fP (const std::string &username, const std::string &password)"
.br
.ti -1c
.RI "void \fBset_proxy_bearer_token_auth\fP (const std::string &token)"
.br
.ti -1c
.RI "void \fBset_logger\fP (Logger logger)"
.br
.ti -1c
.RI "void \fBset_error_logger\fP (ErrorLogger error_logger)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
