.TH "httplib::detail::MatcherBase" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httplib::detail::MatcherBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBhttplib::detail::PathParamsMatcher\fP, and \fBhttplib::detail::RegexMatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatcherBase\fP (std::string pattern)"
.br
.ti -1c
.RI "const std::string & \fBpattern\fP () const"
.br
.ti -1c
.RI "virtual bool \fBmatch\fP (\fBRequest\fP &request) const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
