.TH "httplib::Request" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httplib::Request
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBhas_header\fP (const std::string &key) const"
.br
.ti -1c
.RI "std::string \fBget_header_value\fP (const std::string &key, const char *def='', size_t id=0) const"
.br
.ti -1c
.RI "size_t \fBget_header_value_u64\fP (const std::string &key, size_t def=0, size_t id=0) const"
.br
.ti -1c
.RI "size_t \fBget_header_value_count\fP (const std::string &key) const"
.br
.ti -1c
.RI "void \fBset_header\fP (const std::string &key, const std::string &val)"
.br
.ti -1c
.RI "bool \fBhas_trailer\fP (const std::string &key) const"
.br
.ti -1c
.RI "std::string \fBget_trailer_value\fP (const std::string &key, size_t id=0) const"
.br
.ti -1c
.RI "size_t \fBget_trailer_value_count\fP (const std::string &key) const"
.br
.ti -1c
.RI "bool \fBhas_param\fP (const std::string &key) const"
.br
.ti -1c
.RI "std::string \fBget_param_value\fP (const std::string &key, size_t id=0) const"
.br
.ti -1c
.RI "size_t \fBget_param_value_count\fP (const std::string &key) const"
.br
.ti -1c
.RI "bool \fBis_multipart_form_data\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmethod\fP"
.br
.ti -1c
.RI "std::string \fBpath\fP"
.br
.ti -1c
.RI "std::string \fBmatched_route\fP"
.br
.ti -1c
.RI "Params \fBparams\fP"
.br
.ti -1c
.RI "Headers \fBheaders\fP"
.br
.ti -1c
.RI "Headers \fBtrailers\fP"
.br
.ti -1c
.RI "std::string \fBbody\fP"
.br
.ti -1c
.RI "std::string \fBremote_addr\fP"
.br
.ti -1c
.RI "int \fBremote_port\fP = \-1"
.br
.ti -1c
.RI "std::string \fBlocal_addr\fP"
.br
.ti -1c
.RI "int \fBlocal_port\fP = \-1"
.br
.ti -1c
.RI "std::string \fBversion\fP"
.br
.ti -1c
.RI "std::string \fBtarget\fP"
.br
.ti -1c
.RI "\fBMultipartFormData\fP \fBform\fP"
.br
.ti -1c
.RI "Ranges \fBranges\fP"
.br
.ti -1c
.RI "Match \fBmatches\fP"
.br
.ti -1c
.RI "std::unordered_map< std::string, std::string > \fBpath_params\fP"
.br
.ti -1c
.RI "std::function< bool()> \fBis_connection_closed\fP = []() { return true; }"
.br
.ti -1c
.RI "std::vector< std::string > \fBaccept_content_types\fP"
.br
.ti -1c
.RI "ResponseHandler \fBresponse_handler\fP"
.br
.ti -1c
.RI "ContentReceiverWithProgress \fBcontent_receiver\fP"
.br
.ti -1c
.RI "DownloadProgress \fBdownload_progress\fP"
.br
.ti -1c
.RI "UploadProgress \fBupload_progress\fP"
.br
.ti -1c
.RI "size_t \fBredirect_count_\fP = CPPHTTPLIB_REDIRECT_MAX_COUNT"
.br
.ti -1c
.RI "size_t \fBcontent_length_\fP = 0"
.br
.ti -1c
.RI "ContentProvider \fBcontent_provider_\fP"
.br
.ti -1c
.RI "bool \fBis_chunked_content_provider_\fP = false"
.br
.ti -1c
.RI "size_t \fBauthorization_count_\fP = 0"
.br
.ti -1c
.RI "std::chrono::time_point< std::chrono::steady_clock > \fBstart_time_\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::chrono::time_point<std::chrono::steady_clock> httplib::Request::start_time_"
\fBInitial value:\fP.PP
.nf
=
      (std::chrono::steady_clock::time_point::min)()
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
