.TH "httplib::detail::scope_exit" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httplib::detail::scope_exit
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscope_exit\fP (std::function< void(void)> &&f)"
.br
.ti -1c
.RI "\fBscope_exit\fP (\fBscope_exit\fP &&rhs) noexcept"
.br
.ti -1c
.RI "void \fBrelease\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
