.TH "httplib::MultipartFormData" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httplib::MultipartFormData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBget_field\fP (const std::string &key, size_t id=0) const"
.br
.ti -1c
.RI "std::vector< std::string > \fBget_fields\fP (const std::string &key) const"
.br
.ti -1c
.RI "bool \fBhas_field\fP (const std::string &key) const"
.br
.ti -1c
.RI "size_t \fBget_field_count\fP (const std::string &key) const"
.br
.ti -1c
.RI "\fBFormData\fP \fBget_file\fP (const std::string &key, size_t id=0) const"
.br
.ti -1c
.RI "std::vector< \fBFormData\fP > \fBget_files\fP (const std::string &key) const"
.br
.ti -1c
.RI "bool \fBhas_file\fP (const std::string &key) const"
.br
.ti -1c
.RI "size_t \fBget_file_count\fP (const std::string &key) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "FormFields \fBfields\fP"
.br
.ti -1c
.RI "FormFiles \fBfiles\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
