.TH "httplib::ContentReader" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httplib::ContentReader
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBReader\fP = std::function< bool(ContentReceiver receiver)>"
.br
.ti -1c
.RI "using \fBFormDataReader\fP = std::function< bool(FormDataHeader header, ContentReceiver receiver)>"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBContentReader\fP (Reader reader, FormDataReader multipart_reader)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (FormDataHeader header, ContentReceiver receiver) const"
.br
.ti -1c
.RI "bool \fBoperator()\fP (ContentReceiver receiver) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Reader \fBreader_\fP"
.br
.ti -1c
.RI "FormDataReader \fBformdata_reader_\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
