.TH "httplib::detail::case_ignore::equal_to" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httplib::detail::case_ignore::equal_to
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const std::string &a, const std::string &b) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
