.TH "httplib::DataSink" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
httplib::DataSink
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataSink\fP (const \fBDataSink\fP &)=delete"
.br
.ti -1c
.RI "\fBDataSink\fP & \fBoperator=\fP (const \fBDataSink\fP &)=delete"
.br
.ti -1c
.RI "\fBDataSink\fP (\fBDataSink\fP &&)=delete"
.br
.ti -1c
.RI "\fBDataSink\fP & \fBoperator=\fP (\fBDataSink\fP &&)=delete"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::function< bool(const char *data, size_t data_len)> \fBwrite\fP"
.br
.ti -1c
.RI "std::function< bool()> \fBis_writable\fP"
.br
.ti -1c
.RI "std::function< void()> \fBdone\fP"
.br
.ti -1c
.RI "std::function< void(const Headers &trailer)> \fBdone_with_trailer\fP"
.br
.ti -1c
.RI "std::ostream \fBos\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
